services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=${POSTGRES_DATABASE_NAME}"
      - "POSTGRES_USER=${POSTGRES_DATABASE_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_DATABASE_PASSWORD}"